// Copyright (c) 2026 GameLingo contributors.
// SPDX-License-Identifier: MIT
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart
// ignore_for_file: type=lint, unused_import, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'gl_abi_version': 'gl_abi_version',
  'gl_error_message': 'gl_error_message',
  'gl_is_process_loopback_supported': 'gl_is_process_loopback_supported',
  'gl_list_processes_json': 'gl_list_processes_json',
  'gl_play_wave': 'gl_play_wave',
  'gl_poll_event_json': 'gl_poll_event_json',
  'gl_restore_process_volumes': 'gl_restore_process_volumes',
  'gl_set_process_volume': 'gl_set_process_volume',
  'gl_start': 'gl_start',
  'gl_stop': 'gl_stop',
};
