// Copyright (c) 2026 LoreDub contributors.
// SPDX-License-Identifier: MIT
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart
// ignore_for_file: type=lint, unused_import, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'ld_abi_version': 'ld_abi_version',
  'ld_error_message': 'ld_error_message',
  'ld_is_process_loopback_supported': 'ld_is_process_loopback_supported',
  'ld_list_processes_json': 'ld_list_processes_json',
  'ld_play_wave': 'ld_play_wave',
  'ld_poll_event_json': 'ld_poll_event_json',
  'ld_probe_graphics_json': 'ld_probe_graphics_json',
  'ld_restore_process_volumes': 'ld_restore_process_volumes',
  'ld_set_hotkeys': 'ld_set_hotkeys',
  'ld_set_paused': 'ld_set_paused',
  'ld_set_process_volume': 'ld_set_process_volume',
  'ld_start': 'ld_start',
  'ld_stop': 'ld_stop',
};
