// Copyright (c) 2026 GameLingo contributors.
// SPDX-License-Identifier: MIT

import 'dart:io';

import 'package:ffigen/ffigen.dart';

Future<void> main() async {
  final packageRoot = Platform.script.resolve('../');
  const functions = {
    'gl_abi_version',
    'gl_is_process_loopback_supported',
    'gl_list_processes_json',
    'gl_set_process_volume',
    'gl_restore_process_volumes',
    'gl_play_wave',
    'gl_start',
    'gl_stop',
    'gl_poll_event_json',
    'gl_error_message',
  };
  final generator = FfiGenerator(
    input: Input(
      entryPoints: [packageRoot.resolve('native/game_lingo_native.h')],
      include: (header) => header.path.endsWith('game_lingo_native.h'),
    ),
    visitors: [
      Visitor(
        func: (node) {
          node.isIncluded = functions.contains(node.originalName);
          node.recordUse = node.isIncluded;
        },
      ),
    ],
    output: Output(
      dart: DartOutput(
        path: packageRoot.resolve('lib/src/native/game_lingo_native.g.dart'),
      ),
      recordUseMapping: packageRoot.resolve(
        'lib/src/native/game_lingo_native.record_use_mapping.g.dart',
      ),
      style: const NativeExternalBindings(
        assetId: 'package:game_lingo/src/native/game_lingo_native.g.dart',
      ),
      preamble: '''
// Copyright (c) 2026 GameLingo contributors.
// SPDX-License-Identifier: MIT
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart
// ignore_for_file: type=lint, unused_import, unused_element
''',
    ),
  );
  await generator.generate();
}
